Add button to reset passcode
iteratec/multi-juicer pull request #64
Opened 2020-10-08 15:05 UTC by DerGut

I did some work on #63:
The PR adds a new button to the `<TeamDisplayCard />`.

Clicking it will generate a new passcode, patch the teams juice-shop deployment with the new hash and return the passcode to the user. The passcode will then be displayed via the old but modified `<PasscodeDisplayCard />`.

Looking forward to your feedback!

<img width="801" alt="Screenshot 2020-10-08 at 15 40 56" src="https://user-images.githubusercontent.com/12832754/95476433-887c1400-0987-11eb-8fe9-8ae1ae43401c.png">

2020-10-08 15:13 UTC, J12934 commented
Wow nice 🚀
Will have a closer look later 👍

2020-10-08 19:00 UTC, J12934 requested changes
Seems to be working great 👏
If marked some minor spots where you are using sync code where it could be written asynchronously.


One thing we could potentially change to make this more flexible is to change the `resetPasscode` endpoint to accept the team name as a request argument. This way we could also use the endpoint on the admin page so that an admin can change the passcode of a team.

But this should be flexible enough for now 👍

2020-10-09 11:50 UTC, DerGut commented on juice-balancer/src/teams/teams.js
> +}
Great! 👍  I thought the sync functions would simply await the call behind the scenes. Apparently there is more to it...

2020-10-09 14:27 UTC, J12934 approved these changes

2020-10-09 14:27 UTC, merged

2020-10-09 14:40 UTC, J12934 commented
Merged and released with [v3.8.0](https://github.com/iteratec/multi-juicer/releases/tag/v3.8.0)

Thanks again, much appropriated 🙌

(I've added the [hacktoberfest-accepted](https://hacktoberfest.digitalocean.com/) label to the pr in case you are participating in that)

2020-10-09 15:00 UTC, DerGut commented
Great, thanks! I started to extend the reset-password endpoint for the admin user too. However, I couldn't really find space in the admin table to display the new code 😄 
Perhaps we can track that in #63